# Update the CalendarEvent definition in your public/swagger.yaml file
# Replace the existing CalendarEvent schema with this one:

CalendarEvent:
  type: object
  properties:
    id:
      type: string
      description: Unique identifier for the event
    title:
      type: string
      description: Event title
    start:
      type: string
      format: date-time
      description: Event start time (ISO format)
    end:
      type: string
      format: date-time
      description: Event end time (ISO format)
    allDay:
      type: boolean
      description: Whether this is an all-day event
    resourceId:
      type: string
      description: ID of the associated resource (equipment)
    location:
      type: string
      description: Location where the event takes place
    equipment:
      type: string
      description: Name of the equipment being used
    technician:
      type: string
      description: Name of the technician responsible for the event
    sampleType:
      type: string
      description: Type of sample being processed
    notes:
      type: string
      description: Additional notes or details about the event
    recordId:
      type: string
      description: Reference ID to an external record system
    reminders:
      type: object
      description: Notification/reminder information
      properties:
        useDefault:
          type: boolean
          description: Whether to use default reminders
        overrides:
          type: array
          description: Custom reminder settings
          items:
            type: object
            properties:
              method:
                type: string
                description: Reminder method (email, popup, etc.)
              minutes:
                type: integer
                description: Minutes before event to trigger reminder

# Also update the post /calendar-events schema to include these fields:

post:
  summary: Create calendar event
  description: Creates a new calendar event for a tenant
  operationId: createCalendarEvent
  tags:
    - Calendar Events
  parameters:
    - in: body
      name: body
      description: New event details
      required: true
      schema:
        type: object
        required:
          - tenantId
          - title
          - start
          - end
        properties:
          tenantId:
            type: string
            description: ID of the tenant
          title:
            type: string
            description: Event title
          start:
            type: string
            format: date-time
            description: Event start time (ISO format or 'MMM DD YYYY HH:MM AM/PM' format)
          end:
            type: string
            format: date-time
            description: Event end time (ISO format or 'MMM DD YYYY HH:MM AM/PM' format)
          allDay:
            type: boolean
            description: Whether this is an all-day event
          resourceId:
            type: string
            description: ID of the associated resource (equipment)
          location:
            type: string
            description: Location where the event takes place
          equipment:
            type: string
            description: Name of the equipment being used
          technician:
            type: string
            description: Name of the technician responsible for the event
          sampleType:
            type: string
            description: Type of sample being processed
          notes:
            type: string
            description: Additional notes or details about the event
          recordId:
            type: string
            description: Reference ID to an external record system
          reminders:
            type: object
            description: Notification/reminder information
            properties:
              useDefault:
                type: boolean
                description: Whether to use default reminders
              overrides:
                type: array
                description: Custom reminder settings
                items:
                  type: object
                  properties:
                    method:
                      type: string
                      description: Reminder method (email, popup, etc.)
                    minutes:
                      type: integer
                      description: Minutes before event to trigger reminder
          action:
            type: string
            enum: [create]
            description: Action type (set to 'create' for creating new events)
